gui:
  theme:
    lightTheme: false # For terminals with a light background
    activeBorderColor:
      - magenta
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - default # set to `default` to have no background colour
    selectedRangeBgColor:
      - blue
    cherryPickedCommitBgColor:
      - cyan
    cherryPickedCommitFgColor:
      - blue
    unstagedChangesColor:
      - red
  # Linux specific
  sidePanelWidth: 0.25 # gives you more space to show things side-by-side
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --diff-so-fancy --side-by-side
